trigger:
- main

pool:
  vmImage: windows-latest

steps:


- task: SqlDacpacDeploymentOnMachineGroup@0
  inputs:
    TaskType: 'sqlQuery'
    SqlFile: ' $(System.DefaultWorkingDirectory)\db\dbTable.sql'
    ServerName: 'localhost'
    DatabaseName: 'ASD'
    AuthScheme: 'sqlServerAuthentication'
    SqlUsername: 'asd'
    SqlPassword: '123'
  
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
